### ISSUE TITLE
Add optional provider argument to deploy

### ISSUE THREAD

**Issue by derekflint** [augerai/a2ml#137]
Current api is 

ctx = Context()
a2ml = A2ML(ctx, 'auger,azure')
model_id = 'B20B1E53687048D'
a2ml.deploy(model_id=model_id)

If I have setup a context initially and run import, train. When I get to deploy I must split up context providers before deploy is called.

It would be helpful to leave context and instead have ability to send provider=<provider_name> as argument to deploy to overwrite default context for this command only.

a2ml.deploy(model_id=model_id,provider='auger')

**Comment by vlad-dplrn** [comment]
fixed by https://github.com/augerai/a2ml/pull/203/commits/a9ff408f3a728d779ec7517a08e567ed1e20f558
