### ISSUE TITLE
a2ml.predict with file that does not exist to azure doesn't show error

### ISSUE THREAD

**Issue by derekflint** [augerai/a2ml#144]
When calling predict via API for azure passing a filename value that does not exist it siliently fails.  When calling predict for auger provider it returns correct error.

ctx = Context()
a2ml = A2ML(ctx, 'azure')
model_id = 'AutoML_eda39aa8-ac1d-49b0-bca0-d1d7f622aafb_4'
a2ml.predict(filename='digits_predict.csv',model_id=model_id)

{'azure': {'result': True, 'data': None}}

a2ml = A2ML(ctx, 'auger')
model_id = 'B20B1E53687048D-454554'
a2ml.predict(filename='digits_predict.csv',model_id=model_id)

{'auger': {'result': False,
  'data': "File b'digits_proj/digits_prediction.csv' does not exist"}}

**Expected Behavior**

ctx = Context()
a2ml = A2ML(ctx, 'azure')
model_id = 'AutoML_eda39aa8-ac1d-49b0-bca0-d1d7f622aafb_4'
a2ml.predict(filename='digits_predict.csv',model_id=model_id)

{'azure': {'result': False,
  'data': "File b'digits_proj/digits_prediction.csv' does not exist"}}

**Environment Details:**
 - OS: (e.g. macOS)
 - A2ML Version: (e.g. v0.2.0)
 - Python Version: (e.g. 3.7.5)

**Additional context**

**Comment by skatedplrn** [comment]
fixed in 0.3.6
