### ISSUE TITLE
predict call from pipeline API should accept and return array of hashes

### ISSUE THREAD

**Issue by adamblum** [augerai/a2ml#147]
**Is your feature request related to a problem? Please describe.**
Its a bit strange to have to build and parse CSV files to execute the predict call 

**Describe the solution you'd like**
Accept and return an array of hashes

**Additional context**

**Comment by skatedplrn** [comment]
I suggest to use same parameters as pandas dataframe from_records:
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.from_records.html

def predict(filename, model_id, threshold=None, locally=False, data=None, columns=None)

if data is not None:
  return [{}] #array of hashes

**Comment by skatedplrn** [comment]
fixed in 0.3.6
