### ISSUE TITLE
Specify algorithms to be excluded from an experiement

### ISSUE THREAD

**Issue by rayleeriver** [augerai/a2ml#153]
In Auger.ai console, I can select specific algorithm to be excluded during the training phase.  E.g. I can uncheck SVC and Voting from the lists of selected Algorithms.  However, when creating an Experiment with A2ml, neither config.yaml nor auger.yaml has the option to exclude algorithm(s).

This limits the ability to programmatically train our models via A2ml.  

Please add this support in either YAML files.  Thanks.

**Comment by knobotz** [comment]
Tracking this in #168.
