### ISSUE TITLE
Auger prediction API threw Error 500 after a while

### ISSUE THREAD

**Issue by rayleeriver** [augerai/a2ml#157]
After calling Auger Prediction REST API for a while, we got an Error 500 from API server.  

`17T02:30:00+00:00\",31.0,8.5,null,false,0.0,0,true,0.1601489513,0.8398510487]]}","traceback":"None"},"project_id":1816},"errors":[{"error_type":"fatal","message":"Something` went wrong"}]}} {"status": 500, "request_params": {"status": "success", "result": "{\"columns\":[\"prediction_id\",\"store_id\",\"company_id\",\"gender\",\"employee_age\",\"is_minor\",\"marital_status\",\"race\",\"shift_date\",\"is_weekend\",\"start_time\",\"end_time\",\"unrecorded_no_show_count\",\"default_rate\",\"hire_date\",\"is_holiday\",\"callin_cancel_count\",\"recently_cancel_count\",\"target\",\"proba_False\",\"proba_True\"],\"data\":[[\"0a14e591-6112-48c5-8364-724353672833\",760,91,\"MALE\",17,true,\"SINGLE\",\"BLACK\",\"2020-05-16\",true,\"2020-05-16T19:00:00+00:00\",\"2020-05-17T02:30:00+00:00\",31.0,8.5,null,false,0.0,0,true,0.1601489513,0.8398510487]]}", "traceback": "None", "project_api_token": "****", "id": "198972", "cluster_task": {"status": "SUCCESS", "result": "{\"columns\":[\"prediction_id\",\"store_id\",\"company_id\",\"gender\",\"employee_age\",\"is_minor\",\"marital_status\",\"race\",\"shift_date\",\"is_weekend\",\"start_time\",\"end_time\",\"unrecorded_no_show_count\",\"default_rate\",\"hire_date\",\"is_holiday\",\"callin_cancel_count\",\"recently_cancel_count\",\"target\",\"proba_False\",\"proba_True\"],\"data\":[[\"0a14e591-6112-48c5-8364-724353672833\",760,91,\"MALE\",17,true,\"SINGLE\",\"BLACK\",\"2020-05-16\",true,\"2020-05-16T19:00:00+00:00\",\"2020-05-17T02:30:00+00:00\",31.0,8.5,null,false,0.0,0,true,0.1601489513,0.8398510487]]}", "traceback": "None"}, "project_id": 1816}, "errors": [{"error_type": "fatal", "message": "Something went wrong"}]} on: PATCH /api/v1/cluster_tasks/198972 {"status": "SUCCESS", "result": "{\"columns\":[\"prediction_id\",\"store_id\",\"company_id\",\"gender\",\"employee_age\",\"is_minor\",\"marital_status\",\"race\",\"shift_date\",\"is_weekend\",\"start_time\",\"end_time\",\"unrecorded_no_show_count\",\"default_rate\",\"hire_date\",\"is_holiday\",\"callin_cancel_count\",\"recently_cancel_count\",\"target\",\"proba_False\",\"proba_True\"],\"data\":[[\"0a14e591-6112-48c5-8364-724353672833\",760,91,\"MALE\",17,true,\"SINGLE\",\"BLACK\",\"2020-05-16\",true,\"2020-05-16T19:00:00+00:00\",\"2020-05-17T02:30:00+00:00\",31.0,8.5,null,false,0.0,0,true,0.1601489513,0.8398510487]]}", "traceback": "None"}
5/12/2020, 1:18:15 PM: [2020-05-12 20:18:15,510: INFO/MainProcess] Canceling queue evaluate_trials
5/12/2020, 1:18:16 PM: [2020-05-12 20:18:16,365: INFO/MainProcess] Canceling queue augerml_api
5/12/2020, 1:18:16 PM: [2020-05-12 20:18:16,442: INFO/MainProcess] Canceling queue evaluate_optimizers
5/12/2020, 1:18:16 PM: [2020-05-12 20:18:16,443: INFO/MainProcess] Canceling queue evaluate_api
5/12/2020, 1:18:18 PM: worker: Warm shutdown (MainProcess)
`

**Comment by holyketzer** [comment]
I see this error in our error tracking system, looks like it related with a DB maintenance on Heroku around this time, could you try again.

**Comment by rayleeriver** [comment]
Tried again this morning.  I don't see Error 500 anymore.  Will close this ticket (and open a new once since I'm now encountering a KeyError.
