### ISSUE TITLE
KeyError during Prediction

### ISSUE THREAD

**Issue by rayleeriver** [augerai/a2ml#160]
After running Predictions for a while, I'm starting to get the following KeyError.

`
5/13/2020, 12:07:46 PM: [2020-05-13 19:07:46,639: INFO/ForkPoolWorker-110] Found credentials in environment variables.
5/13/2020, 12:07:47 PM: [2020-05-13 19:07:47,342: WARNING/ForkPoolWorker-110] Prediction threshold: {True: 0.5}, [False, True]
5/13/2020, 12:07:48 PM: [2020-05-13 19:07:48,234: INFO/ForkPoolWorker-110] Task auger_ml.tasks_queue.tasks.predict_by_model_task[a9bfaed3-9518-4080-8643-7af6fae8de7e] succeeded in 1.6719531490234658s: '{"columns":["prediction_id","store_id","company_id","gender","employee_age","is_minor","marital_status","race","shift_date","is_weekend","start_time","end_time","unrecorded_no_show_count","default_rate","hire_date","is_holiday","callin_cancel_count","recently_cancel_count","target","proba_False","proba_True"],"data":[["0c69f496-3fff-4381-a5fa-e79cd08619d5",419,51,"MALE",19,false,"SINGLE","CAUCASIAN","2020-05-15",false,"2020-05-16T00:00:00+00:00","2020-05-16T07:00:00+00:00",12.0,12.0,"2019-08-16",false,0.0,0.0,false,0.6686432586,0.3313567414]]}'
5/13/2020, 12:07:50 PM: [2020-05-13 19:07:50,694: ERROR/ForkPoolWorker-96] Task auger_ml.tasks_queue.tasks.distribution_chart_stats_task[ad374b18-a7ed-4931-b9cf-13848d9ceb18] raised unexpected: KeyError('unrecorded_no_show_count')
5/13/2020, 12:07:50 PM: Traceback (most recent call last):
5/13/2020, 12:07:50 PM: File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 385, in trace_task
5/13/2020, 12:07:50 PM: R = retval = fun(*args, **kwargs)
5/13/2020, 12:07:50 PM: File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 648, in __protected_call__
5/13/2020, 12:07:50 PM: return self.run(*args, **kwargs)
5/13/2020, 12:07:50 PM: File "/var/src/auger-ml-worker/auger_ml/auger_ml/tasks_queue/tasks.py", line 253, in distribution_chart_stats_task
5/13/2020, 12:07:50 PM: date_to=params.get('date_to')
5/13/2020, 12:07:50 PM: File "/var/src/auger-ml-worker/auger_ml/auger_ml/core/model_exporter_ex.py", line 192, in distribution_chart_stats
5/13/2020, 12:07:50 PM: model_path, date_from, date_to, "_*_results.pkl.gz", features, categoricalFeatures
5/13/2020, 12:07:50 PM: File "/var/src/auger-ml-worker/auger_ml/auger_ml/core/model_exporter_ex.py", line 335, in __distribution_stats
5/13/2020, 12:07:50 PM: res[str(curr_date)] = self.__calc_stddev_for_features(stats, features, feature_mapper)
5/13/2020, 12:07:50 PM: File "/var/src/auger-ml-worker/auger_ml/auger_ml/core/model_exporter_ex.py", line 367, in __calc_stddev_for_features
5/13/2020, 12:07:50 PM: res[feature_key]['imp'] = round(stats[feature]['imp'], 6)
5/13/2020, 12:07:50 PM: KeyError: 'unrecorded_no_show_count'
5/13/2020, 12:07:59 PM: [2020-05-13 19:07:59,580: INFO/MainProcess] Received task: auger_ml.tasks_queue.tasks.predict_by_model_task[db8928ee-ce77-426a-83e7-76c8d5c9abc7]  
`

**Comment by holyketzer** [comment]
@rayleeriver good catch!

Actually prediction itself works here so you should have got prediction result, issue here happens after prediction when system collects some statistics. I'm working on fix
