### ISSUE TITLE
SVC times out with large dataset

### ISSUE THREAD

**Issue by rayleeriver** [augerai/a2ml#168]
SVC times out a lot with large dataset size.  In my case just short of 200k rows with k-fold=3.  Per scikit SVC page.. "scales at least quadratically with the number of samples and may be impractical beyond tens of thousands of samples".

Can Auger either automatically disable SVC for large dataset?  or break the dataset down to subset during preprocessing?

Environment:
* a2ml API with Auger provider.

**Comment by knobotz** [comment]
Our plan is to add support in a2ml for excluding algorithms.

**Comment by knobotz** [comment]
@skatedplrn please check if estimate fit time option is available in a2ml.

**Comment by skatedplrn** [comment]
a2ml support blocked_models and allowed_models per provider,
so modify auger.yml:
experiment:
  blocked_models: SVC
