### ISSUE TITLE
Doc: fix a2ml.evaluate

### ISSUE THREAD

**Issue by khizanov** [augerai/a2ml#181]
https://a2ml.org/dev/api.html#a2ml.api.a2ml.A2ML.evaluate 

- problem with formatting Status and Example
- add error status
- describe terminal statuses (completed, interrupted?)
- add usage example:
```
while True:
    status = a2ml.evaluate()
    if status['auger']['data']['status'] not in ['preprocess', 'started']:
        break
```

**Expected Behavior**
-

**Actual Behavior**
-

**Steps to Reproduce the Issue**
1.  Go to the doc page

**Environment Details:**
 - OS: Windows 10
 - Browser: Opera
 - A2ML Version: (e.g. v0.2.0)
 - Python Version: (e.g. 3.7.5)

**Comment by derekflint** [comment]
@khizanov fix in https://github.com/augerai/a2ml/pull/176
