### ISSUE TITLE
REST API should use named arguments

### ISSUE THREAD

**Issue by skatedplrn** [augerai/a2ml#215]
Now it pass:
    def _params(self, *args, **kwargs):
        return {
            'context': jsonpickle.encode(self.ctx),
            'project_name': self.ctx.config.get('name'),
            'args': args,
            'kwargs': kwargs,
        }

instead of args and kwargs params should contains actual name/value args:
res = {
            'context': jsonpickle.encode(self.ctx),
            'project_name': self.ctx.config.get('name')
}
res.update(kwargs)

all provider execute calls should use named arguments:
return self.runner.execute('evaluate', run_id = run_id)

**Comment by holyketzer** [comment]
Not relevant anymore
