### ISSUE TITLE
a2ml.predict() comes back with oh so many possible things from azure

### ISSUE THREAD

**Issue by adamblum** [augerai/a2ml#221]
when there are errors there should be a consistent way of reporting them.

If its  response['azure']['data'] thats fine. if its response['azure']['data']['predicted'] thats fine too

Here are all the branches I have to check to not crash now:

        response = a2ml.predict(filename=None,model_id=A2ML_MODEL,threshold=AUGER_THRESHOLD,data=dicts)
        if isinstance(response, str):
            log.error("Got response from a2ml.predict() back as string")
        else:
            if 'response' in response.keys():
                response=response['response'] 
                log.warning("Response from a2ml.predict() has response key in hash")
            if 'azure' in response.keys() and response['azure'] and response['azure']['data']:
                azure_data = response['azure']['data'] 
                if isinstance(azure_data, str):
                    log.warning("Need keys in azure data")
                else:
                    if 'predicted' in azure_data.keys() and response['azure']['data']['predicted']:
                        log.debug("Response from predict call: %s",response['azure']['data']['predicted'])
                        predictions=response['azure']['data']['predicted']
                        i=0
                        for prediction in predictions: 
                            if store_prediction(prices[i],prediction)>0:
                                log.info("Stored prediction")
                                i = i + 1
                            else:
                                log.error("Failed to stored prediction")
                        return i       
                    else:
                        log.error("No predict hash from Azure data: %s",azure_data) 
            else: 
                log.error("No Azure key in response: %s",response[0:100])
                return None
    else:
        log.error("No option prices for %s on date %s",symbol,date)
        return None

**Comment by knobotz** [comment]
@skatedplrn is this resolved in #243 and #233?
