### ISSUE TITLE
Remove actuals method and provide example how to use actual for one value

### ISSUE THREAD

**Issue by skatedplrn** [augerai/a2ml#258]
Now we have actual and actuals. Let's revert back to actual method:
def actuals(self, model_id, filename=None, actual_records=None, locally=False, provider=None):

Example of how to pass just one record to actual:

actual_records = [[prediction_id, actual_value]]
actuals(model_id, actual_records=actual_records)

**Comment by derekflint** [comment]
@genywind  For clarification I like keeping it 'actuals'. It looks like that is what you plan to do

**Comment by skatedplrn** [comment]
so it will be predict and actuals?

**Comment by derekflint** [comment]
thats a good point, its a bit inconsistent to have predict and actual's'. How about 'actual' then
