### ISSUE TITLE
Support Hub endpoints and review API

### ISSUE THREAD

**Issue by holyketzer** [augerai/a2ml#354]
- Create endpoints
- Create predictions via endpoints API
- Send actuals via endpoints API
- Should we expose to A2ML user `endpoint_id` as an endpoint id or a model id ? 
- Should we continue to support candidate models (to make it work we need `prediction_group_id` on each actual)

cc @knobotz

**Comment by skatedplrn** [comment]
@holyketzer  How to setup endpoint parameters: for example retrain threshold etc?

**Comment by holyketzer** [comment]
It's controlled by review alerts object API

You should create review alert object for it, parameters: 

- `endpoint_id`
- `kind`: `model_accuracy`, `feature_average_range`, `runtime_errors_burst`
- `threshold`: value for triggering, for `model_accuracy` - min accuracy, for `feature_average_range` - deviation in count of std dev's for feature, for `runtime_errors_burst` - max errors count
- `sensitivity`: count of hours the metric must be above/below the threshold to trigger the alert
- `actions`:  `no_actions`, `retrain`, `retrain_deploy`
- `notifications`: `no_notifications`, `user`, `organization`
