### ISSUE TITLE
Feature importance doesn't return anything for ensembles

### ISSUE THREAD

**Issue by holyketzer** [augerai/a2ml#456]
https://app.auger.ai/admin/cluster_tasks/270994

https://app.auger.ai/admin/cluster_tasks/271034

**Comment by skatedplrn** [comment]
This is issue with ensembles - they do not have metrics at all after train

**Comment by skatedplrn** [comment]
fixed in staging, pls check

**Comment by holyketzer** [comment]
https://app-staging.auger.ai/admin/cluster_tasks/144025
