### ISSUE TITLE
Document credentials for all providers and endpoint configurations

### ISSUE THREAD

**Issue by derekflint** [augerai/a2ml#52]
The Readme should show how to setup credentials for all the providers starting with whatever currently works.

- [x] Auger setup

- [x] Azure setup

- [x] Google setup

**Comment by knobotz** [comment]
Quick example table to show what creds are required for what situations... It probably needs better phrasing?

| | Auger AutoML | Azure AutoML | Google Cloud AutoML |
| ------------- | ------------- |------------- |------------- |
| **Auger Cloud Endpoint** | |  | | |
| Provider Credentials Required? | Yes  | No | No |
| |  | ||
| **Self-Hosted Endpoint** | | | |
| Provider Credentials Required? | Yes  | Yes | Yes |
